version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
  # open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
    - dependency-name: "doctrine/orm"
      versions: ["3.x"]
    - dependency-name: "php-di/php-di-name"
      update-types: ["version-update:semver-major"]
